import { StyleSheet } from 'react-native';
import { COLORS } from './adminTheme';

export const modalStyles = StyleSheet.create({
  modal: { flex: 1, backgroundColor: COLORS.canvas },
  modalContent: { maxWidth: 1000, width: '100%', alignSelf: 'center', padding: 36, paddingBottom: 48 },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 26 },
  kicker: { fontSize: 10, color: COLORS.muted, letterSpacing: 1.6, marginBottom: 7 },
  modalTitle: { color: COLORS.ink, fontSize: 26, fontWeight: '700' },
  formGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 14 },
  formSection: { marginTop: 10, marginBottom: 20 },
  formSectionTitle: { color: COLORS.ink, fontSize: 16, fontWeight: '600', marginBottom: 11 },
  uploadRow: { flexDirection: 'row', gap: 10 },
  uploadBox: { width: 140, height: 96, borderWidth: 1, borderColor: COLORS.line, borderStyle: 'dashed', borderRadius: 6, backgroundColor: COLORS.paper, justifyContent: 'center', alignItems: 'center', gap: 6, overflow: 'hidden' },
  uploadBoxFilled: { borderStyle: 'solid' },
  uploadLabel: { color: COLORS.muted, fontSize: 12 },
  preview: { width: '100%', height: '100%', position: 'absolute', resizeMode: 'cover', opacity: 0.42 },
  imageStrip: { flexDirection: 'row', gap: 9, flexWrap: 'wrap', marginTop: 12 },
  previewWrap: { position: 'relative' },
  previewSmall: { width: 64, height: 64, borderRadius: 5 },
  removeImage: { position: 'absolute', right: 6, top: 6, zIndex: 2, elevation: 2, backgroundColor: COLORS.danger, borderRadius: 10, width: 20, height: 20, alignItems: 'center', justifyContent: 'center' },
  chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 13 },
  chip: { borderWidth: 1, borderColor: COLORS.line, backgroundColor: COLORS.paper, borderRadius: 5, paddingHorizontal: 13, paddingVertical: 10 },
  chipActive: { backgroundColor: COLORS.accentSoft, borderColor: '#a7c5b5' },
  chipText: { color: COLORS.muted, fontSize: 13 },
  chipTextActive: { color: COLORS.accent, fontWeight: '600' },
  modalFooter: { flexDirection: 'row', justifyContent: 'flex-end', alignItems: 'center', gap: 12, marginTop: 27, borderTopWidth: 1, borderTopColor: COLORS.line, paddingTop: 20 },
  cancel: { paddingHorizontal: 13, paddingVertical: 10 },
  cancelText: { color: COLORS.muted, fontSize: 14 },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(25,30,26,0.35)', justifyContent: 'center', alignItems: 'center', padding: 20 },
  entityModal: { backgroundColor: COLORS.canvas, width: '100%', maxWidth: 560, borderRadius: 8, padding: 30 },
  uploadLink: { flexDirection: 'row', alignItems: 'center', gap: 7, marginTop: -6, marginBottom: 15 },
  addRow: { color: COLORS.accent, fontSize: 14, fontWeight: '600' },
});
