import type { Brand, Category, Collection, Product } from '@/src/types/database';
import { MaterialIcons } from '@expo/vector-icons';
import { Image, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { Empty, IconButton, PrimaryButton } from './AdminPrimitives';
import { COLORS } from './adminTheme';

type CatalogEntity = Brand | Category | Collection;
export type DashboardData = { products: number; brands: number; categories: number; collections: number; recent: Product[] };

export function DashboardView({ data, onProducts }: { data: DashboardData | null; onProducts: () => void }) {
  if (!data) return <Empty text="No dashboard data available." />;
  const stats = [['Products', data.products, 'watch'], ['Brands', data.brands, 'business'], ['Categories', data.categories, 'category'], ['Collections', data.collections, 'collections']];
  return <><View style={styles.stats}>{stats.map(([label, value, icon], index) => <View style={styles.stat} key={String(label)}><View style={[styles.statIcon, { backgroundColor: index === 0 ? '#e8f0eb' : '#f0eee8' }]}><MaterialIcons name={icon as any} size={22} color={COLORS.accent} /></View><Text style={styles.statValue}>{value}</Text><Text style={styles.statLabel}>{label}</Text></View>)}</View><View style={styles.sectionHeader}><View><Text style={styles.sectionTitle}>Recently added</Text><Text style={styles.sectionSub}>The five most recently created products</Text></View><Pressable onPress={onProducts}><Text style={styles.textButton}>View all products <MaterialIcons name="arrow-forward" size={15} /></Text></Pressable></View><View style={styles.card}>{data.recent.length ? data.recent.map((product) => <View style={styles.recentRow} key={product.id}>{product.image_url ? <Image source={{ uri: product.image_url }} style={styles.thumb} /> : <View style={styles.thumbEmpty}><MaterialIcons name="watch" size={22} color={COLORS.muted} /></View>}<View style={styles.recentInfo}><Text style={styles.rowTitle}>{product.name}</Text><Text style={styles.rowMeta}>{product.brand || 'Unbranded'} · {product.created_at ? new Date(product.created_at).toLocaleDateString() : 'Recently'}</Text></View><Text style={styles.price}>{product.price == null ? '—' : `$${Number(product.price).toLocaleString()}`}</Text></View>) : <Empty text="No products have been added yet." />}</View></>;
}

export function ProductTable({ products, search, setSearch, onAdd, onEdit, onDelete, brands, categories }: { products: Product[]; search: string; setSearch: (value: string) => void; onAdd: () => void; onEdit: (product: Product) => void; onDelete: (id: string) => void; brands: Brand[]; categories: Category[] }) {
  return <><View style={styles.toolbar}><View style={styles.search}><MaterialIcons name="search" size={21} color={COLORS.muted} /><TextInput value={search} onChangeText={setSearch} placeholder="Search products" placeholderTextColor="#a3a59f" style={styles.searchInput} /></View><PrimaryButton label="Add product" icon="add" onPress={onAdd} /></View><View style={styles.card}><ScrollView horizontal showsHorizontalScrollIndicator={false}><View style={{ minWidth: 1100, flex: 1 }}><View style={styles.tableHead}><Text style={[styles.tableLabel, { width: 290 }]}>PRODUCT</Text><Text style={[styles.tableLabel, { width: 160 }]}>BRAND</Text><Text style={[styles.tableLabel, { width: 120 }]}>PRICE</Text><Text style={[styles.tableLabel, { width: 160 }]}>CATEGORY</Text><Text style={[styles.tableLabel, { width: 130 }]}>STRAP</Text><Text style={[styles.tableLabel, { width: 120 }]}>COLOR</Text><Text style={[styles.tableLabel, { width: 110 }]}>ACTIONS</Text></View>{products.length ? products.map((product) => <View style={styles.tableRow} key={product.id}><View style={[styles.productCell, { width: 290 }]}>{product.image_url ? <Image source={{ uri: product.image_url }} style={styles.tableThumb} /> : <View style={styles.tableThumbEmpty}><MaterialIcons name="watch" size={18} color={COLORS.muted} /></View>}<View><Text style={styles.rowTitle} numberOfLines={1}>{product.name}</Text><Text style={styles.rowMeta}>{product.short_name || product.id}</Text></View></View><Text style={[styles.cell, { width: 160 }]}>{product.brand || brands.find((brand) => brand.id === product.brand_id)?.name || '—'}</Text><Text style={[styles.cell, { width: 120 }]}>{product.price == null ? '—' : `$${Number(product.price).toLocaleString()}`}</Text><Text style={[styles.cell, { width: 160 }]}>{categories.find((category) => category.id === product.category_id)?.name || '—'}</Text><Text style={[styles.cell, { width: 130 }]}>{product.strap || '—'}</Text><Text style={[styles.cell, { width: 120 }]}>{product.color || '—'}</Text><View style={[styles.actions, { width: 110 }]}><IconButton icon="edit" onPress={() => onEdit(product)} /><IconButton icon="delete-outline" danger onPress={() => onDelete(product.id)} /></View></View>) : <Empty text="No products match your search." />}</View></ScrollView></View></>;
}

export function EntityGrid({ kind, items, onAdd, onEdit, onDelete }: { kind: 'brands' | 'categories' | 'collections'; items: CatalogEntity[]; onAdd: () => void; onEdit: (item: CatalogEntity) => void; onDelete: (id: number) => void }) {
  return <><View style={styles.toolbar}><Text style={styles.sectionSub}>{items.length} {kind}</Text><PrimaryButton label={`Add ${kind.slice(0, -1)}`} icon="add" onPress={onAdd} /></View><View style={styles.entityGrid}>{items.length ? items.map((item) => <View style={styles.entityCard} key={item.id}>{'logo_url' in item && item.logo_url ? <Image source={{ uri: item.logo_url }} style={styles.entityImage} /> : 'image' in item && item.image ? <Image source={{ uri: item.image }} style={styles.entityImage} /> : <View style={styles.entityImageEmpty}><MaterialIcons name={kind === 'brands' ? 'business' : kind === 'categories' ? 'category' : 'collections'} size={28} color={COLORS.muted} /></View>}<View style={styles.entityBody}><Text style={styles.entityTitle}>{item.name}</Text><Text style={styles.entityDescription}>{'description' in item ? item.description || 'No description' : 'Brand identity'}</Text><View style={styles.entityActions}><IconButton icon="edit" onPress={() => onEdit(item)} /><IconButton icon="delete-outline" danger onPress={() => onDelete(item.id)} /></View></View></View>) : <Empty text={`No ${kind} have been added yet.`} />}</View></>;
}

const styles = StyleSheet.create({
  stats: { flexDirection: 'row', gap: 16, marginBottom: 36, flexWrap: 'wrap' },
  stat: { backgroundColor: COLORS.paper, borderWidth: 1, borderColor: COLORS.line, borderRadius: 8, padding: 20, minWidth: 190, flex: 1 },
  statIcon: { width: 38, height: 38, borderRadius: 8, alignItems: 'center', justifyContent: 'center', marginBottom: 15 },
  statValue: { fontSize: 28, fontWeight: '700', color: COLORS.ink },
  statLabel: { fontSize: 13, color: COLORS.muted, marginTop: 4 },
  sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end', marginBottom: 14 },
  sectionTitle: { color: COLORS.ink, fontSize: 18, fontWeight: '600' },
  sectionSub: { fontSize: 13, color: COLORS.muted, marginTop: 5 },
  textButton: { color: COLORS.accent, fontSize: 13, fontWeight: '600' },
  card: { backgroundColor: COLORS.paper, borderRadius: 8, borderWidth: 1, borderColor: COLORS.line, overflow: 'hidden' },
  recentRow: { flexDirection: 'row', alignItems: 'center', padding: 14, borderBottomWidth: 1, borderBottomColor: COLORS.line },
  thumb: { width: 44, height: 44, borderRadius: 6, marginRight: 12 },
  thumbEmpty: { width: 44, height: 44, borderRadius: 6, backgroundColor: COLORS.canvas, justifyContent: 'center', alignItems: 'center', marginRight: 12 },
  recentInfo: { flex: 1 }, rowTitle: { fontSize: 14, color: COLORS.ink, fontWeight: '600' }, rowMeta: { fontSize: 12, color: COLORS.muted, marginTop: 4 }, price: { fontSize: 14, color: COLORS.ink, fontWeight: '600' },
  toolbar: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 },
  search: { flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.paper, borderWidth: 1, borderColor: COLORS.line, borderRadius: 6, paddingHorizontal: 12, width: 320 },
  searchInput: { flex: 1, paddingVertical: 10, paddingLeft: 8, fontSize: 14, color: COLORS.ink },
  tableHead: { flexDirection: 'row', padding: 13, backgroundColor: '#fafbf9', borderBottomWidth: 1, borderBottomColor: COLORS.line }, tableLabel: { fontSize: 10, color: COLORS.muted, letterSpacing: 1.1 },
  tableRow: { flexDirection: 'row', alignItems: 'center', padding: 12, borderBottomWidth: 1, borderBottomColor: COLORS.line, minHeight: 68 }, productCell: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingRight: 12 }, tableThumb: { width: 42, height: 42, borderRadius: 5 }, tableThumbEmpty: { width: 42, height: 42, borderRadius: 5, backgroundColor: COLORS.canvas, justifyContent: 'center', alignItems: 'center' }, cell: { fontSize: 13, color: COLORS.ink, paddingRight: 10 }, actions: { flexDirection: 'row', gap: 3 },
  entityGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 16 }, entityCard: { width: 280, backgroundColor: COLORS.paper, borderWidth: 1, borderColor: COLORS.line, borderRadius: 8, overflow: 'hidden' }, entityImage: { width: '100%', height: 180, resizeMode: 'contain', backgroundColor: '#f0f1ed' }, entityImageEmpty: { width: '100%', height: 180, backgroundColor: '#f0f1ed', alignItems: 'center', justifyContent: 'center' }, entityBody: { padding: 15 }, entityTitle: { fontSize: 16, fontWeight: '600', color: COLORS.ink }, entityDescription: { color: COLORS.muted, fontSize: 12, marginTop: 6, minHeight: 30 }, entityActions: { flexDirection: 'row', justifyContent: 'flex-end', marginTop: 8 },
});
